### ISSUE TITLE
[Text Input / Dropdown] onBlur not working for text input

### ISSUE THREAD

**Issue by kernelbat** [kyndryl-design-system/shidoka-applications#100]
**Describe the bug**
[Text Input] onBlur not working for text input and dropdown
**To Reproduce**

Component used:
`<TextInput
              onInput={setFormData}
              required={true}
              onBlur={handleBlur}
              name='account'
              value={value}
            />`

**Comment by brian-patrick-3** [comment]
I am unable to replicate this in our Storybook. I can do:
```html
<kyn-text-input @blur=${(e) => console.log(e)>Text Input</kyn-text-input>
```
and I get output in the console.

Please note for the `input` event, you need to capture the custom `on-input` event instead.

**Comment by kernelbat** [comment]
> I am unable to replicate this in our Storybook. I can do:
> 
> ```
> <kyn-text-input @blur="${(e) => console.log(e)">Text Input</kyn-text-input>
> ```
> 
> and I get output in the console.
> 
> Please note for the `input` event, you need to capture the custom `on-input` event instead.
> 
> Are you using [reactify-wc](https://www.npmjs.com/package/reactify-wc) to wrap your components? In that case, you need to bind like this: `on-on-input=` and `on-blur`. Also, we actually recommend [@lit/react](https://www.npmjs.com/package/@lit/react) over reactify-wc now.

we are using [@lit/react]

we have implemented something like given below

`export default createComponent({
  react: React,
  tagName: 'kyn-text-input',
  elementClass: TextInput,
  events: {
    onInput: 'on-input',
   onBlur:'on-blur'
  }
})`

**Comment by brian-patrick-3** [comment]
Ok, thanks for the clarification. I think I see the problem. We don't have a custom `on-blur` event, so just capture the native `blur` event.

**Comment by brian-patrick-3** [comment]
> Please enable this event for textarea and dropdown too

This is not something we need to enable. The native `blur` event will naturally bubble up from the internal `<input>` element.
