### ISSUE TITLE
Tags component don't have the option to change border-radius. Can we add some property to switch between the shape for this ?

### ISSUE THREAD

**Issue by AmirHussain93** [kyndryl-design-system/shidoka-applications#108]
Currently tags look like as below.
<img width="544" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/27803197/70a1bc4c-a217-43e9-9079-2fb884f05a3e">

Would be good if we have the option to make the tag look like as per the UX (screenshot attached)
<img width="562" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/27803197/bf3617b0-26d4-4092-bee4-d0bd849572e4">

Since the element is wrapped inside shadow-root I am unable to over ride the css. And I believe we should not override.

**Describe the solution you'd like**
Would like to have one more property by which we can switch between the tags shape. As of now we have a property **tagSize** which helps us to change the size of tags.

**Describe alternatives you've considered**
I am using carbon design tags component as of now.

**Comment by brian-patrick-3** [comment]
This is the intended design for Tags. You'll need to update your UX to match Shidoka.
