### ISSUE TITLE
[Dropdown] on-change event is getting triggered during initialisation also

### ISSUE THREAD

**Issue by amanagarwal3** [kyndryl-design-system/shidoka-applications#109]
**Describe the bug**

The on-change event for kyn-dropdown is triggering when the dropdown is loaded in HTML, is this expected ? If yes, is there any way to prevent it ?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brian-patrick-3** [comment]
Duplicate of #99
