### ISSUE TITLE
[Form components] invalidText stays even after it is removed

### ISSUE THREAD

**Issue by amanagarwal3** [kyndryl-design-system/shidoka-applications#111]
**Describe the bug**

For the invalidText attribute in text input , there's an issue, the invalid text msg remains in the component even after being deleted, it only goes away after interacting with the component, attaching video 

https://github.com/kyndryl-design-system/shidoka-applications/assets/105861536/710d28c7-7e73-4894-9325-94bd4661c9ce

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brian-patrick-3** [comment]
Is this happening in practice, or only in Storybook? It seems to be only related to the input receiving focus on each keystroke of the Storybook control due to `reportValidity()`.

**Comment by amanagarwal3** [comment]
@brian-patrick-3 It is happening during development as well, the error message stays till the next interaction

**Comment by amanagarwal3** [comment]
@brian-patrick-3 The floating error message popup goes away as expected but the one in caption doesn't till the next change
