### ISSUE TITLE
[Modal] Request for an additional third button

### ISSUE THREAD

**Issue by vrblymt** [kyndryl-design-system/shidoka-applications#115]
I would like a feature where I can define an additional button next to the ok and cancel button.

Example:
![Image](https://github.com/kyndryl-design-system/shidoka-applications/assets/126408222/927a7b46-2ea5-450e-aaf3-9b4dd28c4f14)

**Comment by brian-patrick-3** [comment]
Could you maybe achieve this by instead adding a [Toggle Button](https://kyndryl-design-system.github.io/shidoka-applications/?path=/docs/components-toggle-button--docs) inside the Modal to determine with/without upgrade after closing the Modal with the OK/Primary button?

**Comment by marcosebastianlopez** [comment]
We are looking into this.

**Comment by vrblymt** [comment]
> @vrblymt Could you maybe achieve this by instead adding a [Toggle Button](https://kyndryl-design-system.github.io/shidoka-applications/?path=/docs/components-toggle-button--docs) inside the Modal to determine with/without upgrade after closing the Modal with the OK/Primary button?

It could be an alternative solution yes but it would be good to have this feature too.

**Comment by maulik-thaker1** [comment]
WIP here. PR [#158](https://github.com/kyndryl-design-system/shidoka-applications/pull/158)
