### ISSUE TITLE
[DatePicker]datepicker component gets render differently in MS Edge and Firefox

### ISSUE THREAD

**Issue by redsnapper2006** [kyndryl-design-system/shidoka-applications#116]
**Describe the bug**

datepicker component get render differently in MS Edge and Firefox

**To Reproduce**

1. I use this component in my developed page
2. click the side icon to show calendar
3. calendar gets render differently
4. in addition, date format is different as well.

**Expected behavior**

datepicker component should display in consistent way

**Screenshots**

**Desktop (please complete the following information):**

- Browser [e.g. chrome, safari] : Edge

![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/22907705/2547b812-8e66-4c12-b49b-1aa5ee08f798)

- Browser [e.g. chrome, safari] : Firefox

![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/22907705/051c96e8-c567-4b1c-aa0a-8fde565d5ed7)

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brian-patrick-3** [comment]
This is working as intended. We are using native HTML date and time inputs, which will have different calendar UIs depending on your browser/system. The format of the date you see in the input is based on your locale in addition to browser/system.

Further reference: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date
