### ISSUE TITLE
[OverflowMenu] open upwards if closer to bottom of viewport

### ISSUE THREAD

**Issue by sgoel1495** [kyndryl-design-system/shidoka-applications#117]
**Describe the bug**

Overflow menu gets hidden behind a scroll when its opened on the last row of the table

**To Reproduce**

![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/60220964/9f5df7c9-371a-4b0e-ac0f-d189ff8060f7)

**Comment by brian-patrick-3** [comment]
You can use the `fixed` position property if you want to avoid this.

**Comment by sgoel1495** [comment]
The menu does not scroll with the rows after adding `fixed` prop

**Comment by brian-patrick-3** [comment]
> The menu does not scroll with the rows after adding `fixed` prop 

Yes. That is the trade-off of using fixed position instead of the default absolute position. It would be needlessly expensive to recalculate the menu fixed position on scroll.

**Comment by brian-patrick-3** [comment]
This enhancement has been added. Please note that it works relative to the viewport, not the table container's scroll position.
