### ISSUE TITLE
[Dropdown] Dynamically changing the DropdownOptions throws an error

### ISSUE THREAD

**Issue by sgoel1495** [kyndryl-design-system/shidoka-applications#123]
**Describe the bug**

When we dynamically change the options of a multiselect Dropdown, to be disabled or not based on other fields, it throws an error in the `updated` method.
The error is there for both the case where, value is a blank array or has some value.
The value is also updated to remove the disabled options.
![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/60220964/596aaa38-81a3-4a71-a641-2e2e85f05589)

**Comment by brian-patrick-3** [comment]
I think this needs some more information. The line that error is on only applies to single select dropdowns.

**Comment by sgoel1495** [comment]
Attaching the screenshot with the code used for the `Dropdown`
and yes, the `value` provided to the `Dropdown` is of type `Array<String>`

![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/60220964/e043ff6b-d4d0-4307-860e-d6e77b05ee57)

**Comment by brian-patrick-3** [comment]
I bet it's related to building the options separately. Can you move the options rendering loop so it's inside of the Dropdown instead of it's own function? If the Dropdown renders initially without any options, it could throw this error.

**Comment by sgoel1495** [comment]
tried with the following code, still the same.
![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/60220964/833a343d-4abe-4d43-a11a-cf48343b5cdd)

**Comment by brian-patrick-3** [comment]
This will need some further investigation then. Would you be able to re-create this in a [code sandbox](https://codesandbox.io/) for me?

**Comment by brian-patrick-3** [comment]
In `1.6.11` I added some logic to try and prevent that error. You can try it and see if it helps, but there may still be a larger problem with what you're doing here.

**Comment by sgoel1495** [comment]
Still the same with `1.6.11`
will re-create the issue on code sandbox

**Comment by brian-patrick-3** [comment]
Closing since this issue has gone stale.
