### ISSUE TITLE
Request for ProgressIndicator Component in Shidoka

### ISSUE THREAD

**Issue by nitinsj** [kyndryl-design-system/shidoka-applications#128]
**Is your feature request related to a problem? Please describe.**

We have the following Form progress indicator in our new UI designs.
![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/382907/d09038fc-7a69-450b-8714-6fcc829341e7)

**Describe the solution you'd like**

Add Progress Indicator component to Shidoka Design System.

**Describe alternatives you've considered**

I am currently trying to use [Carbon Progress Indicator](https://react.carbondesignsystem.com/?path=/story/components-progressindicator--default) and facing some (horizointal/vertical) alignment issues with the same.

**Comment by brian-patrick-3** [comment]
Hi there. Please use our AHA Ideas board to request new components: https://kyndrylshidoka.ideas.aha.io/
