### ISSUE TITLE
[Dropdown] Request for searchable variant that filters.

### ISSUE THREAD

**Issue by mrselvamca** [kyndryl-design-system/shidoka-applications#131]
Actual result: Single searchable dropdown always search the full text instead of part of the text and also it just highlighting the searched result with all the options instead of displaying searched text option only.
 
Expected result: Single searchable dropdown should search any part of the string and its display those results only .

Initial Value:
<img width="290" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/162680174/903fa274-f0eb-4ef5-9b94-dabf80722b19">

Search string: 03.20
<img width="290" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/162680174/7fd23e9b-5f76-4ff6-98ef-5f10c8a7f874">

<img width="290" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/162680174/81c56263-04ac-4ea7-9f4f-0cfc5e2eeca7">

Version used on the project - 1.8.0

**Comment by brian-patrick-3** [comment]
This is working as intended, in a way that mimics native `<select>` behavior. 

If you want a filterable variant of the dropdown search, we can treat this as an enhancement request instead.
