### ISSUE TITLE
[DropDown]can not initial a dropdown in disabled state with one dropdownoption selected

### ISSUE THREAD

**Issue by redsnapper2006** [kyndryl-design-system/shidoka-applications#134]
**Describe the bug**

can not initial a dropdown in disabled state with one dropdownoption selected

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**

**Additional context**

**Comment by brian-patrick-3** [comment]
I am unable to reproduce this in our Storybook. Can you provide some more information, or create a reproduction in [CodeSandbox](https://codesandbox.io/)?

**Comment by brian-patrick-3** [comment]
Closing since this issue has gone stale and is still not reproducible with no further details.
