### ISSUE TITLE
[LocalNav] Resize content window based on LocalNav expanded state

### ISSUE THREAD

**Issue by sgoel1495** [kyndryl-design-system/shidoka-applications#136]
is it possible to automatically resize the main content window if the LocalNav is in expanded state?
maybe by providing UIShell with the state of the LocalNav

![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/60220964/0e0ade42-222d-4d7d-8994-42c9d12c16f8)

**Comment by brian-patrick-3** [comment]
Hi there. That actually is exactly what the UI Shell does. You would be able to see it in Storybook, except the Local Nav no longer has pin open functionality in the latest release where it was redesigned, 1.10.x, so this is no longer relevant.
