### ISSUE TITLE
[Header] 2nd level Header Link stating from the top of the page

### ISSUE THREAD

**Issue by sgoel1495** [kyndryl-design-system/shidoka-applications#140]
It would have been better if the `HeaderLink` shown inside Bridge Operations started from where the button is, instead of the top of the page.

![Screenshot (18)](https://github.com/kyndryl-design-system/shidoka-applications/assets/60220964/377ca1b9-8879-4ba2-b2f4-d9c267132a34)

**Comment by brian-patrick-3** [comment]
It shouldn't go above the header, will need to investigate and provide a fix.
