### ISSUE TITLE
[BUG] StickyHeader is not working as expected in table, After enabling it.

### ISSUE THREAD

**Issue by Harshavardhan-Kanoj** [kyndryl-design-system/shidoka-applications#150]
**Describe the bug**

StickyHeader is not working as expected in table, After enabling it.

<kyn-table 
      [striped]="true"
      [stickyHeader]="true"
    >

**Comment by brian-patrick-3** [comment]
Need more information, or a CodeSandbox reproduction.

**Comment by peterpham-kyndryl** [comment]
@Harshavardhan-Kanoj  did  you give the table container a fixed height so that it can scroll? If not, please do so.

**Comment by peterpham-kyndryl** [comment]
@Harshavardhan-Kanoj https://kyndryl-design-system.github.io/shidoka-applications/?path=/story/components-datatable--sticky-header
please look at our story for an example
![Uploading Screenshot 2024-04-17 at 8.45.24 AM.png…]()

**Comment by peterpham-kyndryl** [comment]
![sticky](https://github.com/kyndryl-design-system/shidoka-applications/assets/140734525/7d5f3a15-0100-4845-9c23-bb986307d6c0)

**Comment by brian-patrick-3** [comment]
Closing since this has become stale with no new information.
