### ISSUE TITLE
[Date range picker] Request for Range date picker along with date and time

### ISSUE THREAD

**Issue by ashishpawar12** [kyndryl-design-system/shidoka-applications#152]
We need date range picker with date and time. As of now date range picker is available with date only.

https://kyndryl-design-system.github.io/shidoka-applications/?path=/story/components-date-range-picker--date-range-picker

<img width="1055" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/18259137/322ca241-6cff-46ef-b90f-ca00aa5af66a">

**Comment by ashishpawar12** [comment]
Created Aha ticket
https://kyndrylshidoka.ideas.aha.io/ideas/KSDESIGN-I-49

**Comment by brian-patrick-3** [comment]
Enhancement requests must go in AHA now.
