### ISSUE TITLE
Not able to apply style to increase width of tooltips

### ISSUE THREAD

**Issue by kernelbat** [kyndryl-design-system/shidoka-applications#153]
**Describe the bug**

I want to set style to increase width of tooltip. I tried to apply on Div which I'm passing to it but width of tooltip is not increasing and its preventing internal width from expanding
**To Reproduce**

1. Go to  Tooltip Icon
2. Hover on icon

**Expected behavior**

Either we can set width by passing style to tooltips or it should not prevent child width  from expanding
<img width="877" alt="snip" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/34502376/ad43de6d-89ca-4bfb-84f0-e7a6c037cf6a">

**Screenshots**

**Environment**

**Additional context**

**Comment by brian-patrick-3** [comment]
Web components are encapsulated, so you cannot alter them with external CSS. This is also intentional design, as tooltips are meant to be short and concise.

If you'd like, you can open an enhancement/feature request in AHA for the design team to review.
