### ISSUE TITLE
[Text Input] Request for the text input to support numbers only

### ISSUE THREAD

**Issue by jaideep08** [kyndryl-design-system/shidoka-applications#156]
**Feature enhancement**

The current text input component does not have support for number only scenario, which is defined as follows:

An input(https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input) element of type number are used to let the user enter a number. They include built-in validation to reject non-numerical entries.
The browser may opt to provide stepper arrows to let the user increase and decrease the value using their mouse or by tapping with a fingertip.

Preferred solution:
Similar to this number input from CDS: https://angular.carbondesignsystem.com/?path=/docs/components-number-input--docs

<img width="245" alt="Screenshot 2024-04-23 at 10 26 08 AM" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/71113003/051c9c0e-5624-46a2-8a5a-013d6679516f">

With respect to this AHA ticket: https://kyndrylshidoka.ideas.aha.io/ideas/KSDESIGN-I-45

**Comment by brian-patrick-3** [comment]
Closing this since it is already tracked in AHS.

**Comment by jaideep08** [comment]
Hi @brian-patrick-3, i was asked to create a ticket on github in the mentioned AHA ticket. Hence created one.

**Comment by brian-patrick-3** [comment]
Technically out Text Input well accept type="number", it may just not look great.
