### ISSUE TITLE
[Pagination] when the count is 0, navigation information is not relevant 

### ISSUE THREAD

**Issue by sgoel1495** [kyndryl-design-system/shidoka-applications#165]
ideally it should say `Showing 0-0 of 0 items` and `0 of 0 pages`
![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/60220964/35050e80-b01f-428a-a8ea-53c2dbce8e8c)

**Comment by peterpham-kyndryl** [comment]
@sgoel1495 when there's no data, the default value is 0 if you're NOT passing the pageSize. And if you're passing it, please pass it as 0, too.
https://kyndryl-design-system.github.io/shidoka-applications/?path=/story/components-pagination--pagination&args=count:0;pageNumber:0
<img width="966" alt="Screenshot 2024-05-02 at 9 52 13 PM" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/140734525/d1b45902-e90f-4268-808b-c5c5c7282eac">
