### ISSUE TITLE
[DataTable] Nested table overflow menu coming under parent table row

### ISSUE THREAD

**Issue by bikashp2023** [kyndryl-design-system/shidoka-applications#167]
**Describe the bug**

 Nested table overflow menu coming under parent table row.

![Screenshot 2024-05-01 at 08 30 02](https://github.com/kyndryl-design-system/shidoka-applications/assets/122545343/9303450c-d894-44e6-a9b9-bf11a67db664)

**Environment**

**Additional context**

**Comment by brian-patrick-3** [comment]
What version are you on? I increased the overflow-menu z-index in 1.18.1

**Comment by bikashp2023** [comment]
> What version are you on? I increased the overflow-menu z-index in 1.18.1

yes. 1.18.1

**Comment by brian-patrick-3** [comment]
Would you able to provide some more information, such as if changing any z-indexes resolves it, or provide a CodeSandbox reproduction?

**Comment by bikashp2023** [comment]
@brian-patrick-3 The issue was happening because for the kyn-overflow-menu was using fixed prop as false by default. After i passed the value as true, it works like charm.

**Comment by brian-patrick-3** [comment]
Hmm, it shouldn't be an issue with the standard positioning either though.

**Comment by bikashp2023** [comment]
Closing this issue as i am able to proceed with workaround.
