### ISSUE TITLE
Tooltip does not work with overflow menu

### ISSUE THREAD

**Issue by bikashp2023** [kyndryl-design-system/shidoka-applications#170]
**Describe the bug**
Tooltip does not work with overflow menu

I have use case where i have to show a disabled overflow menu with a tooltip containing the some explanation. The tooltip does not render properly.

![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/122545343/674eba8f-510c-4739-aca2-6771b002ea00)

`   <kyn-overflow-menu-item disabled>
      <kyn-tooltip anchorposition="center" direction="top">
        <div slot="anchor">
          Option1
        </div>
        Tooltip content here.
      </kyn-tooltip>
    </kyn-overflow-menu-item>
    <kyn-overflow-menu-item >
      Option2
    </kyn-overflow-menu-item>
  </kyn-overflow-menu>
`

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**

**Additional context**

**Comment by brian-patrick-3** [comment]
Tooltips were not designed to be used inside of Overflow Menus, so this is simply not going to work.
