### ISSUE TITLE
Text Input:  __isInvalid attribute is not validated correctly on giving an invalid text to the text input field

### ISSUE THREAD

**Issue by Subi1010** [kyndryl-design-system/shidoka-applications#174]
**Describe the bug**

**Text Input:**  __isInvalid attribute is not validated correctly on giving an invalid text to the text input field

I have given a pattern for mail id field and on giving an invalid value to the field, the __isInvalid is evaluating to false which is not correct as it should evaluate to true and vice versa.

![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/73815121/ae589c12-c48b-4735-a32c-65cf55eeb552)

![MicrosoftTeams-image](https://github.com/kyndryl-design-system/shidoka-applications/assets/73815121/00f5d6a9-5781-4719-8cd9-cfe153c03ef8)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**

**Additional context**

**Comment by brian-patrick-3** [comment]
Would you mind copy/pasting your RegEx pattern, and some strings to test against?

**Comment by Subi1010** [comment]
**Pattern:** ^[a-zA-Z0-9\.]+@kyndryl\.com$
**Valid Input:** test@kyndryl.com,test1@kyndryl.com
**Invalid Input:** test@kyn.com,test1@kyndryl.comy

**Comment by Subi1010** [comment]
This issue is across all Invalid check for the Text Input field. Not just for a pattern check, it exists during duplicate check as well for Text Input field.

**Comment by brian-patrick-3** [comment]
Does the error message show in the UI? _isInvalid is an internal property, so you should not be referencing it externally. 

Our Storybook Docs page for Forms under Patterns has information about how to check and trigger native form validations.

**Comment by Subi1010** [comment]
No, the isInvalid property is referenced for an event to checkFormValidity.

**Comment by brian-patrick-3** [comment]
Using this pattern on the Text Input in our Storybook Patterns/Forms page, I can see the pattern mismatch error message in the UI on input, and it shows the message and focuses the input on clicking Submit (which executes `document.querySelector('form').reportValidity()`). This is functioning correctly. 

Again, you should not be referencing the `_isInvalid` property externally (anywhere in your code) as it is an internal/private property.  More information on Form Validation here: http://localhost:6006/?path=/docs/patterns-forms--docs#validation

**Comment by Subi1010** [comment]
ok.......{ [element.name]: !element.isInvalid && element.value?.length > 0  }, Are we not allowed to access the isInvalid like this?

**Comment by brian-patrick-3** [comment]
> ok.......{ [element.name]: !element.isInvalid && element.value?.length > 0 }, Are we not allowed to access the isInvalid like this?

Correct. It is not a public property. Properties that you can interface with are all documented in Storybook.

**Comment by Subi1010** [comment]
May I know what property can be used to check if a field is invalid given a pattern? Because I don't see any property in the list as invalidText is for custom use.

**Comment by brian-patrick-3** [comment]
> May I know what property can be used to check if a field is invalid given a pattern? Because I don't see any property in the list as invalidText is for custom use.

There isn't one. You must use the HTML Constraint Validation API as I've previously mentioned, and linked to in our docs.
