### ISSUE TITLE
close event for inline notification

### ISSUE THREAD

**Issue by amanagarwal3** [kyndryl-design-system/shidoka-applications#175]
Is there any event which gets triggered when clicking on the close button of inline kyn-notification ?

**Comment by maulik-thaker1** [comment]
Not emits any event yet as it's internal method to close entire notification. @brian-patrick-3  do we need to emit any event while closing **inline** and **toast** notification ?

**Comment by brian-patrick-3** [comment]
Yeah we'll need to add a close event
