### ISSUE TITLE
when multi dropdown is disabled, it should not allow interactions with tags or chips.

### ISSUE THREAD

**Issue by bikashp2023** [kyndryl-design-system/shidoka-applications#176]
**Describe the bug**

Clicking on close icons on tag or in the chips changes the dropdown value. It should restrict user changing it.

![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/122545343/3698f3bd-d754-4020-ac7c-b4113286327e)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment**

**Additional context**

**Comment by brian-patrick-3** [comment]
Clicking the X in a Tag is treated the same as de-selecting the item in the dropdown. This is working as intended.

**Comment by bikashp2023** [comment]
why it should allow when the dropdown is disabled ?

**Comment by brian-patrick-3** [comment]
Ah I missed the disabled part. Sorry!
