### ISSUE TITLE
Issue in Kyn-checkbox

### ISSUE THREAD

**Issue by sindhujatce** [kyndryl-design-system/shidoka-applications#177]
**Describe the bug**
<img width="245" alt="Screenshot 2024-05-20 at 11 47 32 AM" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/47389264/72221034-db07-4f6e-8b3a-54defa01d8c8">

In the above, all three checkbox options are checked on load, which should autocheck the selectAll check box too. But currently, selectAll is not checked. 

**To Reproduce**

<kyn-checkbox-group name="Status" invalidtext="" selectAll="true">
      <span slot="label">Label</span>
        <kyn-checkbox [checked]="true"
        value="option1" class="kd-type--body-02">
        <span title="option1">
          Option1
        </span>
    </kyn-checkbox>
      <kyn-checkbox [checked]="true"
      value="option2" class="kd-type--body-02">
      <span title="option2">
        Option2
      </span>
  </kyn-checkbox>
      <kyn-checkbox [checked]="true"
      value="option3" class="kd-type--body-02">
      <span title="option3">
        Option3
      </span>
  </kyn-checkbox>
    </kyn-checkbox-group>
1. Try this above code
2. options are selected, but selectAll is unselected

**Expected behavior**

when All checkbox options are auto selected, selectAll should also needs to be autoselected,when one or two options is auto selected, selectAll checkbox also needs to be selected and shown with (-) symbol.

Added the screenshot in the beginning.

**Environment**

- OS: macOS
- Browser : Chrome
- Version 124.0.6367.203 (Official Build) (arm64)

**Additional context**

**Comment by brian-patrick-3** [comment]
I can't reproduce this in our Storybook. Link: https://kyndryl-design-system.github.io/shidoka-applications/?path=/story/components-checkbox--checkbox-group&args=selectAll:!true

The Select All checkbox has the correct state on load. Make sure you are specifying the `value` array for the initial selections.

**Comment by sindhujatce** [comment]
@brian-patrick-3  when I am passing the checked Attribute as true in any of the checkbox options, selectAll checkbox needs to be auto checked, that's not happening.

**Comment by brian-patrick-3** [comment]
> @brian-patrick-3  when I am passing the checked Attribute as true in any of the checkbox options, selectAll checkbox needs to be auto checked, that's not happening.

This is incorrect. You must control selections through the value prop on the checkbox group.

**Comment by sindhujatce** [comment]
Thanks for the info, with value props, its working now
