### ISSUE TITLE
[SideDrawer], Header is hidden behind table header and Button with icon

### ISSUE THREAD

**Issue by sgoel1495** [kyndryl-design-system/shidoka-applications#181]
Initial State:
![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/60220964/538af8ef-d81e-49fa-bef7-06361711ca42)

After Scroll:

![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/60220964/a09460c2-73c6-46bb-a374-a835d6d2b478)
![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/60220964/8b567647-3208-4d4a-ba78-e63bce9eebc6)

**Comment by brian-patrick-3** [comment]
It looks like you've included the content above the table within your scrollable table container.

**Comment by sgoel1495** [comment]
Hi @brian-patrick-3 
No we haven't included the button inside the table container.
