### ISSUE TITLE
[DATEPICKER] format mismatch for different users on same browser 

### ISSUE THREAD

**Issue by vaishnavi-dhakankar** [kyndryl-design-system/shidoka-applications#183]
**Describe the bug**
we have used the date picker and date range picker at couple of places in GTM
however its observed that the format of the placeholder and selected value shown on the component is different on MAC vs Windows
As per UX we need mm/dd/yyyy however on MAC we see it as dd/mm/yyyy and windows its .mm/dd/yyyy (both firefox and chrome) 

**Expected behavior**
the date format visible to all users should be same ie mm/dd/yyyy.

**Screenshots**
for MAC 
<img width="750" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/d594d0be-5e5f-4623-aead-a85ee592a081">

for Window
![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/a02497b9-726d-4fdb-8b9a-7d843d54ff80)

**Environment**
- OS -Mac
- Browser - chrome,firefox

**Comment by vaishnavi-dhakankar** [comment]
@maulik-thaker1 please look into this issue

**Comment by maulik-thaker1** [comment]
@vaishnavi-dhakankar we used native `<input type="date">`. So format is depends on browser. For more info see below
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date
