### ISSUE TITLE
[DATERANGEPICKER] Unable to reset the value for the range picker 

### ISSUE THREAD

**Issue by vaishnavi-dhakankar** [kyndryl-design-system/shidoka-applications#184]
**Describe the bug**

we have used the date range picker at couple of places in GTM
however its observed that we are unable to reset the value of start and end date of the range picker

we used it in a modal with two buttons - apply and cancel. on apply the set value is saved to a variable however on cancel we need to clear the date range picker. For this we passed an empty string but it doesn't clear the component

**Expected behavior**

need to reset the value on some event

**Screenshots**
we selected the values for the date range picker and it gets set as required (for ref printed just above the date range):
<img width="703" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/45064d6a-6ed1-4f57-9f41-608cdc1703cb">

now on click of cancel we reset the value of the date range picker, the value is updated and is passed as empty to the component but the value doesn't reset( for ref printed just above the date range).
<img width="619" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/5b70bfb8-280c-4b8b-b343-547a847a8b99">

**recording for reference**
https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/6f15684b-1b70-46db-b8c8-46d08b68733e

**Environment**

- OS: Mac
- Browser:  chrome

**Comment by brian-patrick-3** [comment]
@maulik-thaker1  User-entered values may not get cleared unless the `<input>` `value` is also cleared. text-input and text-area have dealt with this same type of issue.

**Comment by maulik-thaker1** [comment]
> @maulik-thaker1 User-entered values may not get cleared unless the `<input>` `value` is also cleared. text-input and text-area have dealt with this same type of issue.

ok will check this.

**Comment by maulik-thaker1** [comment]
@vaishnavi-dhakankar Resolved this in [v1.24.5](https://github.com/kyndryl-design-system/shidoka-applications/releases/tag/v1.24.5)
