### ISSUE TITLE
[Tag] Tag label gets truncated

### ISSUE THREAD

**Issue by vaishnavi-dhakankar** [kyndryl-design-system/shidoka-applications#187]
**Describe the bug**

We used Shidoka tag in a couple of places in GTM-UI, and the text is sometimes truncated.
Shidoka should allow us to customise the number of characters after which it can truncated into ellipses

**To Reproduce**

Steps to reproduce the behaviour:

1. Go to Shidoka library
2. Click on Tag
3. Add a very long text for the tag label
4. the text gets truncated beyond certain characters

**Expected behavior**

**Screenshots**
<img width="1637" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/640a31db-f1a4-4f9e-ba33-f71d4b7a29f5">

**Comment by brian-patrick-3** [comment]
This is not a bug. This is an intentional design decision to limit the number of characters in a tag. If you disagree, please [raise an enhancement request in AHA](https://kyndrylshidoka.ideas.aha.io) for the design team to evaluate.

**Comment by maulik-thaker1** [comment]
more info here ( in guideline tab ) : https://kyndryl.gitbook.io/shidoka-design-system/components/application/tags
