### ISSUE TITLE
Dropdown required asterisk symbol shows as non red when the field is not disabled.

### ISSUE THREAD

**Issue by bikashp2023** [kyndryl-design-system/shidoka-applications#200]
**Before submitting a bug:**

- [X] Is this reproducible in the latest version of Shidoka?
- [X] Is this reproducible in the [Shidoka Storybook](https://kyndryl-design-system.github.io/shidoka-applications/)?
- If it's not reproducible in any of the above scenarios, please do not open a bug report as it is an application-level issue.

**Describe the bug**

Required asterisk symbol for dropdown is getting displayed with grey color instead of red when it is not disabled.

**To Reproduce**

![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/122545343/491fab62-29e5-4b2d-957e-6dd6bc84b07c)

**Comment by brian-patrick-3** [comment]
Resolved in 1.27.2
