### ISSUE TITLE
Dark Background when Modal Opened through Overflow Menu Option

### ISSUE THREAD

**Issue by guptaashray** [kyndryl-design-system/shidoka-applications#201]
**Before submitting a bug:**

- Shidoka Version 1.27.0
- Sandbox Link - https://codesandbox.io/p/devbox/kyn-overflow-options-modal-l8h4r6

**Describe the bug**
When I click on Overflow Menu Option, a modal pop-up is opened. The background is too dark in that case, otherwise when I open a modal normal, on any other scenario, the background is not that dark.

**To Reproduce**
Go to sandbox link.
Click on any option of OverFlow Menu in the table rows.

**Expected behavior**
The background should not be that dark.

**Screenshots**
<img width="1425" alt="MicrosoftTeams-image (1)" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/43576436/cd8ff9c9-ba63-43e4-820e-99874d191dbf">
<img width="1055" alt="MicrosoftTeams-image (2)" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/43576436/8ea00f92-50df-41dd-8a52-d15e94a2991f">
<img width="1150" alt="MicrosoftTeams-image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/43576436/a162560a-ed79-436a-8b43-33490872de09">

**Comment by brian-patrick-3** [comment]
The issue based on the shared sandbox is that a modal is being opened for every single row all at once. Not a bug, but an implementation issue.
