### ISSUE TITLE
[Checkbox][filterable] Select all not working as expected

### ISSUE THREAD

**Issue by vaishnavi-dhakankar** [kyndryl-design-system/shidoka-applications#204]
**Before submitting a bug:**

- [x] Is this reproducible in the latest version of Shidoka? 
- [x] Is this reproducible in the [Shidoka Storybook](https://kyndryl-design-system.github.io/shidoka-applications/)? 
- [ ] Is this reproducible in a [Sandbox](https://codesandbox.io)?
- If it's not reproducible in any of the above scenarios, please do not open a bug report as it is an application-level issue.

**Describe the bug**

'Select all' checkbox is displayed and clickable even when there are no results found for the search text.
Also checking the checkbox 'select all'  after filtering text is entered has no matching option it selects all options in the group. (ref recording) 

<img width="1240" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/ae9a404f-4c2f-4404-8409-b62575d34682">

<img width="1240" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/7af06bfe-174f-4e22-983f-8898b62aec94">

https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/6171ab1f-e757-4d48-95fa-370b06e71518

**To Reproduce**

1. Go to 'shidoka storybook'
2. select on 'checkbox'
4. set filterable to true in controls
5. enter string not matching any option
6. See issue

**Expected behavior**

Either the 'select all' checkbox should not disabled when no options are available or it should be hidden with msg mentioning no options.

**Screenshots**

**Environment**

**Additional context**

**Comment by brian-patrick-3** [comment]
This is intended behavior. Select all is meant to select every option, ignoring the search/filter.
