### ISSUE TITLE
[Textarea] Max length Number is going out of the border if we set width of textarea

### ISSUE THREAD

**Issue by kernelbat** [kyndryl-design-system/shidoka-applications#205]
**Before submitting a bug:**

- [ ] Is this reproducible in a [Sandbox](https://codesandbox.io)?
- If it's not reproducible in any of the above scenarios, please do not open a bug report as it is an application-level issue.

**Describe the bug**

After setting width in style for textarea, max length indicator gets overlapped with scroll if we add more rows  to it.  Even when we drag to resize it, max length number goes out of its border  line. It happens only when we set width for textarea

**To Reproduce**

After Resizing:
![image](https://github.com/user-attachments/assets/3f399fc9-9d35-490c-841d-8c14787a16a0)

After entering multiple rows:
![image](https://github.com/user-attachments/assets/59cba74b-8fa5-4ff3-848f-8001f061d0a8)

**Expected behavior**

Is there any way to show set fullwidth to it

**Screenshots**

Please refer sandbox code and try to resize it:
https://codesandbox.io/p/sandbox/sad-jones-str6nc?file=%2Fsrc%2FApp.tsx%3A18%2C35
**Environment**

**Additional context**

**Comment by brian-patrick-3** [comment]
Are you talking about manually resizing the textarea by grabbing the lower right hook with your mouse? This is unavoidable in that case, because the indicator is positioned relative to the container, not the actual input.

**Comment by kernelbat** [comment]
Yes, So basically indicator is positioned relative to container,  due this it is also overlapping on scroll too as given in second screenshot.

**Comment by brian-patrick-3** [comment]
We cannot change the relative position, but can maybe add some more right padding to prevent overlap with scrollbar at the initial size.
