### ISSUE TITLE
[Data Table] Overflow Menu not fully visible

### ISSUE THREAD

**Issue by ashishpawar12** [kyndryl-design-system/shidoka-applications#206]
**Before submitting a bug:**

- [x] Is this reproducible in the latest version of Shidoka?
- [x] Is this reproducible in the [Shidoka Storybook](https://kyndryl-design-system.github.io/shidoka-applications/)?
- [x] Is this reproducible in a [Sandbox](https://codesandbox.io)?
- If it's not reproducible in any of the above scenarios, please do not open a bug report as it is an application-level issue.

**Describe the bug**

Overflow menu when opening upward not fully visible

**To Reproduce**

https://codesandbox.io/p/devbox/data-table-jj8dq2?file=%2Fsrc%2Fapp%2Fapp.component.ts%3A57%2C7

<img width="1440" alt="image" src="https://github.com/user-attachments/assets/441b3b8a-8ae6-476b-9492-998c82bf6d49">

**Comment by brian-patrick-3** [comment]
This is expected behavior due to absolute position within a scrolling container. The only alternative is to use the fixed position tooltip variant.
