### ISSUE TITLE
Shidoka dropdown is not working on ipad 9th generation device

### ISSUE THREAD

**Issue by Bhanu220290** [kyndryl-design-system/shidoka-applications#217]
**Before submitting a bug:**

- [ Yes] Is this reproducible in the latest version of Shidoka?
- [Yes ] Is this reproducible in the [Shidoka Storybook](https://kyndryl-design-system.github.io/shidoka-applications/)?
- [ ] Is this reproducible in a [Sandbox](https://codesandbox.io)?
- If it's not reproducible in any of the above scenarios, please do not open a bug report as it is an application-level issue.

**Describe the bug**
Shidoka's dropdown component is not working neither on safari nor on chrome browser in ipad 9th generation device. i tested it on browser stack 

https://github.com/user-attachments/assets/f4aaf702-0f06-437f-8109-f403d3a2ea7e

**To Reproduce**

1. Go to https://www-pre.kyndryl.com/us/en/bridge
2. select any Service provider
3. Click on Dashboard
4. Click on Quotations (make sure you must have Admin rights to check)
5. Select any Quotation whose status is Cancelled, Draft etc
6. it will redirect you to Quotation detail page
7. select HistoryLog, there you fill find the issue in Filter section
8. See error

**Expected behavior**

**Screenshots**

**Environment**

- OS: [e.g. iOS] - 9th Generation ipad
- Browser [e.g. chrome, safari] - Don't know because i checked on Browser stack

**Additional context**

![shidoka_dropdown_issue](https://github.com/user-attachments/assets/d802337d-67e7-4cf4-a1a4-0917cf0ad192)

**Comment by brian-patrick-3** [comment]
The ElementInternals API is only supported in Safari 16.4 and later.
