### ISSUE TITLE
SwiperConfig is not getting imported

### ISSUE THREAD

**Issue by Shubhamjain20135** [kyndryl-design-system/shidoka-applications#251]
**Before submitting a bug:**

- [x] Is this reproducible in the latest version of Shidoka? yes
- [x] Is this reproducible in the [Shidoka Storybook](https://kyndryl-design-system.github.io/shidoka-applications/)? yes
- [ ] Is this reproducible in a [Sandbox](https://codesandbox.io)?
- If it's not reproducible in any of the above scenarios, please do not open a bug report as it is an application-level issue.

**Describe the bug**

I want to use carousel from the shidoka applications https://kyndryl-design-system.github.io/shidoka-applications/?path=/docs/patterns-carousel--docs

SwiperConfig is not getting imported even though latest shidoka application is installed.

**Expected behavior**

SwiperConfig should be imported

**Screenshots**

<img width="1316" alt="image" src="https://github.com/user-attachments/assets/1c4d49ea-6a5c-4e33-8dd9-dc565c79b047">

<img width="1315" alt="image" src="https://github.com/user-attachments/assets/fb898f80-2d58-4009-804d-8b16b2a770a5">

**Comment by brian-patrick-3** [comment]
It looks like it's just a typo: `shdioka` should be `shidoka`
