### ISSUE TITLE
FormData is not recognising form elements having name attribute as variable 

### ISSUE THREAD

**Issue by bikashp2023** [kyndryl-design-system/shidoka-applications#40]
**Describe the bug**

I have created a shidoka form with just a text input and submit button. The text-input's attributes are getting it's values from Angular property binding. The attributes like caption, placeholder etc are reflecting on the UI; but the only problem is when we define name property with property binding; then FormData is giving you empty value. If we change name attribute to static value, it works fine.

Below is the code sandbox example created. Once you type some text in the textinput and click on submit button, then formData is printed as blank. If you remove property binding from "name" and use static string; it prints the value of the field.

Note: This is a contrive example, but what i meant is to read each form elements attribute from JSON.

[Codesandbox link](https://codesandbox.io/p/devbox/tender-tdd-qyxrm6?embed=1&file=%2Fsrc%2Fapp%2Fapp.component.html%3A8%2C1&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clpr3y51h00093b6kqhw25p4c%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clpr3y51h00023b6kgs0j91le%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clpr3y51h00073b6kdkd2kzpq%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clpr3y51h00083b6k9vmc4jzg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B58.98351977228289%252C41.01648022771711%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clpr3y51h00023b6kgs0j91le%2522%253A%257B%2522id%2522%253A%2522clpr3y51h00023b6kgs0j91le%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpr4ebgb00pj3b6kmpgjhmj6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A8%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A8%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Fapp%252Fapp.component.html%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpr4ebgb00pj3b6kmpgjhmj6%2522%257D%252C%2522clpr3y51h00083b6k9vmc4jzg%2522%253A%257B%2522id%2522%253A%2522clpr3y51h00083b6k9vmc4jzg%2522%252C%2522activeTabId%2522%253A%2522clpr4hu49003x3b6kordt8esc%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A4200%252C%2522id%2522%253A%2522clpr4hu49003x3b6kordt8esc%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%252C%2522clpr3y51h00073b6kdkd2kzpq%2522%253A%257B%2522id%2522%253A%2522clpr3y51h00073b6kdkd2kzpq%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clpr3y51h00033b6k1voo6fx7%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522start%2522%257D%252C%257B%2522id%2522%253A%2522clpr3y51h00043b6kpb9r7nuz%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522build%2522%257D%252C%257B%2522id%2522%253A%2522clpr3y51h00053b6kp8bd5n2m%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522test%2522%257D%252C%257B%2522id%2522%253A%2522clpr3y51h00063b6k4f2rg17l%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522help%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522npm%2520install%2520%2540kyndryl-design-system%252Fshidoka-foundation%25401.0.0%2522%252C%2522id%2522%253A%2522clpr42n4h00db3b6kiiehg9ua%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clpr3y51h00033b6k1voo6fx7%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brian-patrick-3** [comment]
This one is strange, I am unable to reproduce it in our Storybook environment using variable name assignment. @peterpham-kyndryl @maulik-thaker1 curious if you might have any ideas.
