### ISSUE TITLE
[Form fields] Request for control over label text case

### ISSUE THREAD

**Issue by bikashp2023** [kyndryl-design-system/shidoka-applications#41]
**Is your feature request related to a problem? Please describe.**
I am creating a form consisting of questions  as part of label and answer's in the form of form elements like textArea, textInput etc.
In shidoka the label is always in uppercase and  can not control the spacing between the label and form element. The workaround is giving the label value as blank and create a separate html element representing label. This works, but when the form element is mandatory then the red dot is still getting displayed against the blank label.  Since this is a web component and all the styles are shielded from out side modification, Is there a way to hide this ?

![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/122545343/cc4a0153-c00e-4af8-966c-dd508cae1335)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by brian-patrick-3** [comment]
There is currently no way to hide the label. The label is required for Accessibility compliance.

Is there a reason you need to customize the label? The built-in label style and position is based on the design system guidelines, and customizing it would break compliance.

**Comment by brian-patrick-3** [comment]
> @brian-patrick-3 The only problem with the label is it would be in upper case though i can try doing case conversion via javascript

That's correct. Unless the designers want to add a variant, you're stuck with uppercase.

I would strongly discourage trying to modify it in any way. Web components are encapsulated to prevent modifications. If we decide to expose customizations, we will create a way for that to happen.

**Comment by cunningham-kyndryl** [comment]
@bikashp2023  what use case are you trying to solve? And the use of uppercase is a style guide rule and shouldn't be altered. Are you asking for a more condensed title/label format?

**Comment by bikashp2023** [comment]
@cunningham-kyndryl The usage of these form elements in my cases are in questionaries. So the form element labels should be the case that i supply without converting to uppercase.

![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/122545343/0540b31c-a762-485b-af15-5e5ec7cdcca1)
