### ISSUE TITLE
Button inside Overflow menu slot is not visible and menu item's are exposed 

### ISSUE THREAD

**Issue by bikashp2023** [kyndryl-design-system/shidoka-applications#44]
**Describe the bug**

I have created an overflow menu inside a table, but the button containing "..." svg is not visible. This issue i am getting when my containerise angular application is running inside cloud, whereas it works perfectly fine in my mac in the container.

Attached the snap comparison obfuscating irrelevant part.

Version of  "@kyndryl-design-system/shidoka-applications": "^1.1.4"

**Docker Container in Cloud** **(NOT WORKING)**

![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/122545343/94f4e7fa-fd82-4447-bb38-1851efa808d2)

vs

**Docker container in Mac** **(WORKING)**

![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/122545343/67185b1e-bf62-46a7-aa0e-015bd398c9f6)

**Comment by brian-patrick-3** [comment]
Since this is working correctly in your local development environment, I can only assume the issue must be related to your deployment pipeline or cloud environment. I don't think this is something our team will be able to help you with.
