### ISSUE TITLE
StoryBook 'Show Code' under the Docs section does not display the expected html code

### ISSUE THREAD

**Issue by nitinsj** [kyndryl-design-system/shidoka-applications#49]
**Describe the bug**

The Show Code section under Docs section of DataTable does not show the Pagination related source code.

**To Reproduce**

1. Go to https://kyndryl-design-system.github.io/shidoka-applications/?path=/docs/components-data-table--docs#data-table
2. Click on 'Show code' button on the right bottom corner.
3. Scroll down to Code section.
4. See the Code.

**Expected behavior**

The code should display the **Pagination related HTML tags** (code).

**Screenshots**

<img width="1488" alt="Screenshot 2023-12-15 at 11 15 03 AM" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/382907/11e0a73f-ee9b-4383-a88a-b12ebc3da31b">

**Comment by brian-patrick-3** [comment]
Hi there. The Show Code option on the Docs page is limited, because it only shows compiled output. Take a look at individual stories, and the Code tab in the Addons panel, to see the original source.
