### ISSUE TITLE
Should invalidText attribute of the form element make a pristine untouched element invalid ?

### ISSUE THREAD

**Issue by bikashp2023** [kyndryl-design-system/shidoka-applications#51]
**Describe the bug**

I suppose invalidText value should be shown when the form element is touched and when the value is still empty. But currently if the required attribute is true and invalidText is provided then on load the form element becomes invalid. Let me know if it is done intentionally.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brian-patrick-3** [comment]
Our form elements provide some default built-in validations to try and match native functionality. Ex: required, pattern, min, max.  The `invalidText` property is intended for custom validations, and it will be visible when a non-empty string is given.
