### ISSUE TITLE
The action overflow menu in a data-table is going below pagination

### ISSUE THREAD

**Issue by bikashp2023** [kyndryl-design-system/shidoka-applications#55]
**Describe the bug**

Couple of issue are there:
1- The overflow menu is going under the pagination option.
2- There is a large gap between the last row of the table and the pagination option.

Here is the snap taken from storybook.

![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/122545343/750b43fa-a03b-4eb4-a457-ba3cabb2bfa8)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brian-patrick-3** [comment]
This seems to need two different considerations:

1. We need to prevent the closed menu from taking up space.
2. When used within a container with `overflow: scroll/auto`, like the data table, the menu opens within the scrollable area, potentially hidden. We can add an option to used `position: fixed` instead of absolute, but that will have some caveats of it's own we need to be careful of. This is because `position: fixed` will make the menu relative to the window, rather than the anchor.

**Comment by brian-patrick-3** [comment]
I changed the animation to use `transform: scale` so it has no height when hidden. I also added a `fixed` prop that you can enable, but I would recommend trying without it first.

**Comment by bikashp2023** [comment]
Hi @brian-patrick-3, this mostly resolves the issue except in the last row; where the overflow goes under pagination and dragging it up brings the white space.

<img width="1430" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/122545343/e41194ae-f6a8-4600-b6a0-3d65225282af">

**Comment by brian-patrick-3** [comment]
> Hi @brian-patrick-3, this mostly resolves the issue except in the last row; where the overflow goes under pagination and dragging it up brings the white space.
> <img alt="image" width="1430" src="https://private-user-images.githubusercontent.com/122545343/292527590-e41194ae-f6a8-4600-b6a0-3d65225282af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyNjI3MDYsIm5iZiI6MTcwMzI2MjQwNiwicGF0aCI6Ii8xMjI1NDUzNDMvMjkyNTI3NTkwLWU0MTE5NGFlLWY2YTgtNDYwMC1iNmEwLTNkNjUyMjUyODJhZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMlQxNjI2NDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNzdmMmVjNWU4NTVmMGQ2YmFmZmRmOTZmYWI3YTZjYTQzM2QzYTA5ZGM5ZmZiMDE2NmNmMGMxNTgzM2RhZTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pnHYFarga8KRO3p2EIU2cOFJFCozJoDCs9nZ_Ue-f1M">

That's correct. With relative absolute positioning, the menu renders within the scrollable container. The only way around that is to use the new `fixed` property, which has it's own caveats that I mentioned already.
