### ISSUE TITLE
We need a provision to update the value of dropdown programmatically

### ISSUE THREAD

**Issue by vaishnavi-dhakankar** [kyndryl-design-system/shidoka-applications#56]
We need a provision to update the value of the dropdown programmatically

I am using the multi-select dropdown as part of the filtering modules for the page.
In Shidoka updating the dropdown selection is possible with only user clicks, However, we require a way to clear or update the selection based on single button click. 
Since this is a web component and all the styles are shielded from outside modification, Is there a way to update the options ?

**Comment by brian-patrick-3** [comment]
Any time the slotted child options change, the dropdown value should recalculate. So however you are controlling the rendering of the child elements, updating those and setting the `selected` attribute should accomplish what you need.

**Comment by vaishnavi-dhakankar** [comment]
As mentioned used the `selected` attribute of the option '' component to update the selection programmatically. It seems to clear the checkboxes but not the tags. And on selecting a new option it reselects all previous options


after user selection
<img width="392" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/4ba37eec-055c-46e9-b736-c5da3812928a">
<img width="322" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/75849c55-a66a-42f1-9336-6951da71470b">


on programmatic reset to the original state by setting `selected` to false
<img width="392" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/6091a91a-56f1-450e-b50d-8ed2ddda3792">

**Comment by brian-patrick-3** [comment]
I discovered that the `slotchange` event which we use to reset the dropdown does not trigger when modifying child nodes (dropdown options), only when adding or removing them. To accommodate this scenario, I've exposed the `resetSelection` method so that you can call it manually. 

Example:
```js
document.querySelector('kyn-dropdown').resetSelection();
```

**Comment by vaishnavi-dhakankar** [comment]
Is this a workaround for now and will this bug be fixed later? 
As ideally we should be updating the dropdowns related changes inside the component itself instead of using a document object to trigger the component.
If this behaviour changes in future we might have more complexities and bugs in portal.

**Comment by brian-patrick-3** [comment]
It was built this way intentionally to match how a native `<select multiple>` gets updated, by setting the `selected` attribute on each `<option>`.
