### ISSUE TITLE
Request for prop to hide the tags below multi-select dropdown

### ISSUE THREAD

**Issue by vaishnavi-dhakankar** [kyndryl-design-system/shidoka-applications#57]
I am creating a filtering module with multiple multi-select dropdowns. The dropdowns mentioned add tags at the bottom for selected options. As per UX provided for the page required us to add another selection with all the selected options.

In shidoka the tags are always added and there is duplication of tags. Therefore need a provision to hide the tags of selected options under the dropdown component (multi-select variant )

<img width="378" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/516de0a3-ca95-41e7-9010-8f5d6a570377">

<img width="779" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/a8c9ad37-2ce7-4517-a3f8-b268394bfa9c">

**Comment by brian-patrick-3** [comment]
Since this is the intended design for the multi-select, we will have to raise this to the design team as an enhancement request.

**Comment by cunningham-kyndryl** [comment]
@vaishnavi-dhakankar  can you give us the use case in more detail? It's not clear when or how this use case gets used.

**Comment by vaishnavi-dhakankar** [comment]
@cunningham-kyndryl As per the design shared with us, we need to show all the selected options from multiple dropdowns in a separate section with a single clear action to clear the selection. 

design  below:
<img width="368" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/b5016793-09f9-41a9-ad9b-f959bbce47ea">

however, with the current implementation of Shidoka dropdown, we see additional tags (blue tags) just below the dropdown 
(see previous img) which causes duplication of tags. We want a flag based on which we could show/hide these blue tags.

**Comment by brian-patrick-3** [comment]
> @vaishnavi-dhakankar can you show the design that needs this? In the DD, the user can unselect all sections by clicking on the black tag within the DD. Does this not solve that problem?

I think they want to be able to reset all of the dropdowns/filters with on click, whereas the black tag in the dropdown only clears that one dropdown.

**Comment by vaishnavi-dhakankar** [comment]
@brian-patrick-3 @cunningham-kyndryl  I have already discussed it Robert and Manoj, they will get back to you for further discussion.
