### ISSUE TITLE
Width of the dropdown changes on selecting options

### ISSUE THREAD

**Issue by vaishnavi-dhakankar** [kyndryl-design-system/shidoka-applications#58]
while working with the multi-select dropdown noticed that the width of the dropdown increased based on the number of options selected.
The workaround is adding a dropdown within a fixed width div or container. however, it still doesn't solve the issue of min-width of the dropdown which is too less. Since this is a web component and all the styles are shielded from outside modification,  is there a way to specify the minimum width ?

1. Add a multi-select dropdown
2. select multiple options.
3. see issue of increasing width 

screenshots
<img width="304" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/61cfb1af-f164-465b-bd1f-fe1de07b3641">

<img width="304" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/293a44e4-50d8-4f2f-b33b-e8b43f845b4e">

<img width="439" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/30548673-8ec1-4916-bbed-b2b80f724c3a">

**Comment by brian-patrick-3** [comment]
This is the correct behavior for an inline element. What you can do is specify your own width on the host tag, and/or use it within a grid layout.
