### ISSUE TITLE
Kyndryl Bridge logo is required in Header and Footer components

### ISSUE THREAD

**Issue by hbdevfrk** [kyndryl-design-system/shidoka-applications#60]
**Describe the bug**
Support for Kyndryl Bridge logo instead of Kyndryl logo in header and footer components of Shidoka

In header and footer components, we wish to have the Kyndryl Bridge logo instead of the Kyndryl logo that currently shows up. Can you please share if it is already supported?

Current logo in kyn-header:
![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/155367390/ceb24bd9-585d-4552-ad06-db753989c278)

Expected logo for us:
![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/155367390/525547e0-a9e4-426d-af62-e9a2b65ea7e0)

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome
- Version: 120.0.6099.130

**Comment by brian-patrick-3** [comment]
You can find the kyndryl bridge logo within the shidoka-foundation package. From there, you can import it into your application and slot it into the header to override the default logo.

**Comment by hbdevfrk** [comment]
Sure, will check. Thanks!
