### ISSUE TITLE
[Data Table] Add disabled prop for selectable rows

### ISSUE THREAD

**Issue by bikashp2023** [kyndryl-design-system/shidoka-applications#61]
**Is your feature request related to a problem? Please describe.**

We have got a requirement where the rows are enabled or disabled conditionally. Is that supported in shidoka data table. I see the property in table-row, but it not used anywhere.

<img width="418" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/122545343/5d861221-29f3-4bc3-97bc-866a58845024">

**Comment by brian-patrick-3** [comment]
I discovered that while the `disabled` prop exists, it doesn't appear to actually do anything.

**Comment by peterpham-kyndryl** [comment]
> I discovered that while the `disabled` prop exists, it doesn't appear to actually do anything.

The absence of 'rows disabled' functionality in the table isn't a bug, as it wasn't included in the original designs. To determine the appropriate color schemes for both the default and striped tables, we will need input from the UX team.

**Comment by brian-patrick-3** [comment]
> The absence of 'rows disabled' functionality in the table isn't a bug, as it wasn't included in the original designs. To determine the appropriate color schemes for both the default and striped tables, we will need input from the UX team.

Ok. Let's at least remove that prop from the docs in the meantime then to avoid confusion.

**Comment by brian-patrick-3** [comment]
Removed the unused table-row `disabled` prop from the docs temporarily until the feature can get implemented.

**Comment by brian-patrick-3** [comment]
Blocked by #90.

**Comment by bikashp2023** [comment]
Initially, the requirement aimed to distinguish inactive records from active ones by rendering inactive rows as non-interactable. However, our updated UI specifications now focus solely on displaying active records, rendering this feature request obsolete.
