### ISSUE TITLE
Icons in secondary navigation are not aligned with the text

### ISSUE THREAD

**Issue by hbdevfrk** [kyndryl-design-system/shidoka-applications#62]
**Describe the bug**

Icons show up but out of alignment within secondary navigation.

**To Reproduce**
Add carbon icons (React) to Secondary navigation item

1. Hover on Secondary navigation
2. Notice the icons are not aligned with the text

**Expected behavior**

After adding the icon, the icon should be aligned with the text as shown in Storybook

**Screenshots**

<img width="197" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/155367390/3799f805-1491-469b-84e2-401fd1ed925b">

**Desktop (please complete the following information):**

- OS: Windows 11
- Browser: Chrome

**Additional context**

```
import { Add } from '@carbon/icons-react'
const LitKynLocalNav = reactifyWc('kyn-local-nav')
const LitKynLocalNavLink = reactifyWc('kyn-local-nav-link')
```

```
  <LitKynLocalNavLink 
                href={`${basePath}${link.link}`} 
                active={index === selected} 
                key={link.label} 
                onClick={() => notificationService.closeNotification()}
              >
                <Add size={32}/>
                {link.label}
  </LitKynLocalNavLink>
```

**Comment by brian-patrick-3** [comment]
You need to add `slot="icon"` to the icon, like in our storybook example. Also, use size 20 icons in the local nav, not 32.
