### ISSUE TITLE
Request for mutiselect dropdown with select all option

### ISSUE THREAD

**Issue by ashishpawar12** [kyndryl-design-system/shidoka-applications#64]
**Is your feature request related to a problem? Please describe.**
I need option of select All on drop down with multi select. on click of All option other options should be selected automatically.

<img width="247" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/18259137/f1fb7e00-bd7d-497f-a3da-a8de59962bbe">

**Comment by brian-patrick-3** [comment]
Hi there. I don't think this is something we would want to build into the component, but you should be able to achieve this externally by hooking into the `on-change` event and manually updating the `selected` attribute of your options.

**Comment by ashishpawar12** [comment]
Yes @brian-patrick-3 that was last possibility to invoke from our side on change event to update other options selection. Thanks will try to implement same way. I was just checking if it easier to available or not.

**Comment by brian-patrick-3** [comment]
We will build in a native Select All option at some future date.
