### ISSUE TITLE
Multiple drodown with resetselection not working properly

### ISSUE THREAD

**Issue by ashishpawar12** [kyndryl-design-system/shidoka-applications#70]
**Describe the bug**

I have tried to add all options on multiple dropdown and tried to checked unchecked option programmatically with reset selection as per suggestion with Shidoka Team. But after adding changes though values are not getting updated properly on dropdown and tag both. specifically found scenario as below

**Steps to reproduce**
First click on select All
after that click on option1. It will unchecked option1 along with option4(last option) though selected value is true for option4
After that try to checked option1 and again try to unchecked option1 it will automatically unchecked option3 which was last selected options on dropdown

And Even close icon with number of selection is also not reflecting correct value

**Note**: i have observed last selected option is getting unchecked automatically.
 

**To Reproduce**

Please refer attached screen record and sample code zip for more details

**Comment by ashishpawar12** [comment]
[shidoka-sample-angular copy 2.zip](https://github.com/kyndryl-design-system/shidoka-applications/files/13935542/shidoka-sample-angular.copy.2.zip)

**Comment by ashishpawar12** [comment]
https://github.com/kyndryl-design-system/shidoka-applications/assets/18259137/28efb0b0-39b7-479b-9078-9dfd3fdd2f41

**Comment by ashishpawar12** [comment]
https://github.com/kyndryl-design-system/shidoka-applications/assets/18259137/106b4164-67a5-4fa1-a8a7-39cb2240344d

**Comment by brian-patrick-3** [comment]
I added [a story with a working "All Option" example](https://kyndryl-design-system.github.io/shidoka-applications/?path=/story/components-dropdown--all-option) after making a couple code changes. You can [see the full code example in this custom component](https://github.com/kyndryl-design-system/shidoka-applications/blob/main/src/components/reusable/dropdown/testDd.ts) I built for this example. The key will be to call `resetSelection()` after the `kyn-dropdown-option` updates [complete their render cycle](https://github.com/kyndryl-design-system/shidoka-applications/blob/c692ff25b68768979a6868eae3bb2dd41176c530/src/components/reusable/dropdown/testDd.ts#L80).

**Comment by ashishpawar12** [comment]
Thanks @brian-patrick-3

**Comment by ashishpawar12** [comment]
@brian-patrick-3 while deselecting other option like option1 its not deselecting all option. same case if all other options are selected then 'Select all' options should all so get selected

<img width="1440" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/18259137/faf35490-7743-454b-b605-76ca177eacb1">
