### ISSUE TITLE
Request for Radio/Checkbox Group horizontal alignment option

### ISSUE THREAD

**Issue by AmirHussain93** [kyndryl-design-system/shidoka-applications#73]
**Is your feature request related to a problem? Please describe.**

Yes. I am using **kyn-radio-button-group** and by default the radio buttons are aligned vertically. Is there any way to align the radio buttons horizontally?

**Describe alternatives you've considered**
I tried over riding css but it doesn't work since the **fieldset** which holds this radio buttons is wrapped inside a **shadow-root**.

Can you please let me know if there is any way to align the radio buttons horizontally ?

**Additional context**

<img width="991" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/27803197/41e2d039-490b-47ec-a774-56d2848e93d0">

**Comment by brian-patrick-3** [comment]
There is no option for a horizontal layout for Radio or Checkbox groups currently. We can raise this to the design team as an enhancement request.
