### ISSUE TITLE
Feature request : Modal pop-up configurable button colors (v1.2.2)

### ISSUE THREAD

**Issue by AbhishekDuraphe** [kyndryl-design-system/shidoka-applications#76]
**Is your feature request related to a problem? Please describe.**
With latest release which includes modal pop-up, I am trying to implement the design as the shared screenshot.
<img width="712" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/3701798/70226926-cf8b-49b1-a230-eaf30578ff04">

I am unable to change the color of OK button to destructive (Red). 
As its an element rendered under shadow root its not customisable.

**Describe the solution you'd like**
If I am allowed to add custom actions under 'actions' slot, I should be able to hide or remove the default actions (OK/CANCEL).
*OR*
Color customisation should be available for default actions.

**Comment by brian-patrick-3** [comment]
We will add a `destructive` prop to the modal component to alter the OK button style.
