### ISSUE TITLE
Request for addition of Tag/Badge component 

### ISSUE THREAD

**Issue by vaishnavi-dhakankar** [kyndryl-design-system/shidoka-applications#78]
As per UX we require a badge component to show the status of the asset. 

<img width="368" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/154880624/616db461-8771-4686-ba9f-225b5fe2310d">

**Comment by maulik-thaker1** [comment]
It's in progress. [#91](https://github.com/kyndryl-design-system/shidoka-applications/pull/91). Will update once done.
