### ISSUE TITLE
Request for any working example of 'no data found' for Data table and Skeleton kind of loading for data table

### ISSUE THREAD

**Issue by ashishpawar12** [kyndryl-design-system/shidoka-applications#80]
**Is your feature request related to a problem? Please describe.**

Is there any story or example where i can show no data found for data table and also loader/skeleton kind of loading for data table?

**Comment by brian-patrick-3** [comment]
The [Figma file for Data Tables](https://www.figma.com/file/CQuDZEeLiuGiALvCWjAKlu/Applications---Component-Library?node-id=4078%3A158651&mode=dev) has examples of this. I would not expect skeleton loading components to be available any time soon as we even don't have generic loading indicators yet.

**Comment by ashishpawar12** [comment]
Ok Thanks @brian-patrick-3
