### ISSUE TITLE
Kyndryl Dropdown Item Overflowing from Dropdown

### ISSUE THREAD

**Issue by guptaashray** [kyndryl-design-system/shidoka-applications#81]
**Describe the bug**
Longer text items are overflowing from the Kyndryl Dropdown.

**Expected behavior**

It should appear the same way it appears in the dropdown, but after selecting the longer text option, the text overflows.

**Screenshots**

<img width="1484" alt="Screenshot 2024-02-08 at 4 27 10 PM" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/43576436/ddd8c17c-bf65-45aa-8263-63bd347cccac">

<img width="1726" alt="Screenshot 2024-02-08 at 4 27 52 PM" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/43576436/821aa586-c92f-4915-9bed-eaf056f52f62">

**Comment by brian-patrick-3** [comment]
I think this is a duplicate of #71 which has a fix that was already released.

**Comment by guptaashray** [comment]
Yes, it was raised by one of my team members only.
We are currently using the following versions - 

"@kyndryl-design-system/shidoka-applications": "^1.3.0",
"@kyndryl-design-system/shidoka-foundation": "^1.3.6",

And we are facing this issue!

**Comment by brian-patrick-3** [comment]
You can see here, if I set a width on `kyn-dropdown`, it correctly overflows with an ellipsis:

![Screenshot 2024-02-08 082722](https://github.com/kyndryl-design-system/shidoka-applications/assets/126408222/ee0b7d8e-e491-4224-8893-32967ec18448)

**Comment by brian-patrick-3** [comment]
Also, please be aware that not having a label breaks accessibility compliance.

**Comment by guptaashray** [comment]
Yes, I was not using Label because of which the accessibility was breaking. Thanks a lot!
