### ISSUE TITLE
Datepicker input format and saved data formats are different

### ISSUE THREAD

**Issue by bikashp2023** [kyndryl-design-system/shidoka-applications#84]
**Describe the bug**

Datepicker input format and saved data format are different.
The selection of datepicker format is "dd/mm/yyyy" but the "on-change" event receives data in "yyyy-mm-dd" format. So every time we have to load back from the saved data, we have to convert from one format to other.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brian-patrick-3** [comment]
The actual selection is probably using a format specific to your current locale, whereas the output value is a specific format which tries to be more generic. It would probably work best to convert any date strings to JS Date objects. If you have a better suggestion for the output format, we're open to suggestions.
