### ISSUE TITLE
Request for a File Upload Component

### ISSUE THREAD

**Issue by AmirHussain93** [kyndryl-design-system/shidoka-applications#85]
**Is your feature request related to a problem? Please describe.**
If use doesn't wants to update data manually he can just upload a file. Currently I don't see a File Uploader component in storybook.

File uploaders allow users to upload content of their own. A file uploader is commonly found in forms, but can also live as a standalone element. 

**Describe the solution you'd like**
User should have an option to upload a file

**Describe alternatives you've considered**
We are using file uploader provided ny carbon design system currently

**Additional context**
Attaching screenshot for reference 

<img width="563" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/27803197/3ebb9f29-4c70-4373-82dc-2eafee6e9314">

**Comment by brian-patrick-3** [comment]
Please use AHA to request new components now: https://kyndrylshidoka.ideas.aha.io/ this is where we will determine priority based on votes.
