### ISSUE TITLE
  Unable to modify the input placeholder in Multi Select Searchable Component

### ISSUE THREAD

**Issue by AmirHussain93** [kyndryl-design-system/shidoka-applications#86]
**Is your feature request related to a problem? Please describe.**
Yes. I don't see the option to modify the text in input field for this component if any of the option is selected. 

I tried checking the various options available in story book.  Place holder text can be modified but how to modify the text of input field similar to the screenshot attached if any or all of the options are selected ? This is the requirement as per the UX.

**Describe the solution you'd like**
Would like to update the text of input if one or more items are selected. I am attaching the screenshot below for reference

**Additional context**
<img width="526" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/27803197/7a45ec88-08d9-455e-86b6-979c8feb6cdd">

**Comment by brian-patrick-3** [comment]
The multi-select dropdown already has a specific style for showing selected count, by adding a badge before the placeholder which can be clicked to deselect all. The `placeholder` attribute will override the "Select Items" default placeholder.

**Comment by AmirHussain93** [comment]
@brian-patrick-3 the UX screen shot I have shared is given by the UX team. In this case I think the UX needs to be updated ?

**Comment by brian-patrick-3** [comment]
> @brian-patrick-3 the UX screen shot I have shared is given by the UX team. In this case I think the UX needs to be updated ?

That's right
