### ISSUE TITLE
Clear field action still active with disabled=True in TextInput field

### ISSUE THREAD

**Issue by sgoel1495** [kyndryl-design-system/shidoka-applications#87]
**Describe the bug**

After providing `disabled={true}` to `TextInput` component,
Clear icon on the right side is still visible and clickable as well and triggers the `on-input` event

**To Reproduce**

![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/60220964/9a257df0-e4ad-4184-b32b-394348369345)

**Expected behavior**

Clear Icon on the right side of the Input field should disappear if `disabled={true}` props is provided

**Screenshots**

![image](https://github.com/kyndryl-design-system/shidoka-applications/assets/60220964/6f9972ea-6b27-4fbe-965c-b47a1a189e9f)

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Edge
- Version: 121.0.2277.106

**Comment by brian-patrick-3** [comment]
Note: If a Boolean property is always going to be `true`, you can just add the attribute (ex: `<tag disabled></tag>`). You don't have to bind it unless it's a variable that you might change.
