### ISSUE TITLE
[Forms] Fix form validation reporting for inputs that have not been interacted with yet

### ISSUE THREAD

**Issue by bikashp2023** [kyndryl-design-system/shidoka-applications#88]
**Describe the bug**

Is there a standard API exposed which would tell if the form and/or form elements valid ?

I am creating a form using all sorts of form elements like input, text area, dropdown, radio etc. I need to know if the individual form element are valid and overall form is valid state or not; no required field should be empty. So is there a standard method exposed to check for each element or form ?  Please note that it should expose whether form elements are pristine or dirty.

  Currently i do get the validity of the form using a hack by attaching listener to each element and if check the form element is required and it's not empty or not. I am sure it is not the best solution. Do we have any alternative ?

Ex:

<img width="850" alt="image" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/122545343/93aaba11-545d-43b4-8b98-1460d76e9d19">

**Comment by brian-patrick-3** [comment]
@bikashp2023 did this answer your question, or is there anything outstanding?

**Comment by bikashp2023** [comment]
@brian-patrick-3 `form.checkValidity()` or `form.reportValidity()` would always suggest the form is valid; even if the required form elements are pristine (not touched). So visually if there is red validation error it would say the form is invalid, otherwise it would always be valid. 
So my take is the form should be invalid if there is required field which is not filled.

**Comment by brian-patrick-3** [comment]
Hmm right, because we wait til user entry to validate. We'll need to decouple that so you get the correct valid state from reportValidity, but any invalid fields that haven't been interacted with yet will not be updated to show the internal error message which is a problem. Need to think on this a bit. @kyndryl-design-system/ui-devs curious if you have any ideas here.
