### ISSUE TITLE
<kyn-tooltip></kyn-tooltip>, when I use this tooltip , by default icon symbol is coming, which should not come.

### ISSUE THREAD

**Issue by Harshavardhan-Kanoj** [kyndryl-design-system/shidoka-applications#93]
**Describe the bug**

**<kyn-tooltip></kyn-tooltip>, when I use this tooltip , by default icon symbol is coming, which should not come.**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by brian-patrick-3** [comment]
Tooltip anchors are always intended to be info icons. You can customize it using the `anchor` slot to place a different sized info icon if needed.

**Comment by Harshavardhan-Kanoj** [comment]
the carbon <cds-tooltip></cds-tooltip> was allowing us to put inside any component,
like example
<cds-tooltip [description]="'Hello world!">
  <h3> Hello word</h3>
 </cds-tooltip>
 however it's not possible to add same way in <kyn-tooltip></kyn-tooltip>

**Comment by Harshavardhan-Kanoj** [comment]
<img width="1728" alt="Screenshot 2024-02-16 at 9 43 36 AM" src="https://github.com/kyndryl-design-system/shidoka-applications/assets/121387705/d090f8ab-bc66-4f8b-8d31-c86a29c09a43">

@brian-patrick-3 , you can see in the above image,  They applied tooltip tip to child button.
https://angular.carbondesignsystem.com/?path=/docs/components-tooltip--docs
The similar way how can we able to add it?

**Comment by brian-patrick-3** [comment]
As I said, the official design direction is tooltip anchors must always be an info icon.
