### ISSUE TITLE
[Dropdown] Margin applied on Label tag in Dropdown without a label

### ISSUE THREAD

**Issue by sgoel1495** [kyndryl-design-system/shidoka-applications#98]
**Describe the bug**

The div tag for label in Dropdown has `marginBottom` applied even if there is no label

**Expected behavior**

Styles to the label container should not be applied if the label is not present

**Screenshots**

![Screenshot (13)](https://github.com/kyndryl-design-system/shidoka-applications/assets/60220964/3d300ec2-1458-4241-919e-442739471a19)

**Comment by brian-patrick-3** [comment]
Hi there. The label is required for accessibility purposes. You cannot have any form fields without a label.
